# States the game can be in
INSTRUCTIONS_PAGE_0 = 0
INSTRUCTIONS_PAGE_1 = 1
GAME_RUNNING = 2
GAME_OVER = 3

# Game constants
SCREEN_TITLE = "SnakeParty RPG"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
MERGE_SPRITES = True

# Sprite sizes
TEAM_SPRITE_SCALING = 0.5
TEAM_SPRITE_SIZE = 32 * TEAM_SPRITE_SCALING
ENEMY_SPRITE_SCALING = TEAM_SPRITE_SCALING
WALL_SPRITE_SCALING = 1
WALL_SPRITE_SIZE = 32 * WALL_SPRITE_SCALING

# Grid sizes
GRID_WIDTH = 35
GRID_HEIGHT = 35
AREA_WIDTH = int(GRID_WIDTH * WALL_SPRITE_SIZE)
AREA_HEIGHT = int(GRID_HEIGHT * WALL_SPRITE_SIZE)

# How fast things move
MOVEMENT_SPEED = 5
JAVELIN_SPEED = 7

# How close the player can get to the edge before wall
VIEWPORT_MARGIN = 300
