# States the game can be in
INSTRUCTIONS_PAGE_0 = 0
INSTRUCTIONS_PAGE_1 = 1
GAME_RUNNING = 2
GAME_OVER = 3

# Sprite sizes
SPRITE_SCALING = 0.5
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)

SCREEN_WIDTH = SPRITE_SIZE * 14
SCREEN_HEIGHT = SPRITE_SIZE * 10
# SPRITE_SCALING = 1
# SPRITE_SIZE = SPRITE_SCALING
TEAM_SPRITE_SCALING = SPRITE_SCALING * 3
TEAM_SPRITE_SIZE = TEAM_SPRITE_SCALING
ENEMY_SPRITE_SCALING = TEAM_SPRITE_SCALING
WALL_SPRITE_SCALING = SPRITE_SCALING
WALL_SPRITE_SIZE = WALL_SPRITE_SCALING

# Game constants
SCREEN_TITLE = "SnakeParty"
# SCREEN_WIDTH = 800
# SCREEN_HEIGHT = 600
WINDOW_WIDTH = SCREEN_WIDTH + 100
WINDOW_HEIGHT = SCREEN_HEIGHT + 100
MERGE_SPRITES = True
OFFSCREEN_SPACE = 200
LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = SCREEN_WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = SCREEN_HEIGHT + OFFSCREEN_SPACE

# Amt. of enemies when first encounter
STARTING_IMP_COUNT = 3

# Stats default
STARTING_HP = 50
STARTING_LIVES = STARTING_IMP_COUNT

# Grid sizes
GRID_WIDTH = 35
GRID_HEIGHT = 35
AREA_WIDTH = int(GRID_WIDTH * WALL_SPRITE_SIZE)
AREA_HEIGHT = int(GRID_HEIGHT * WALL_SPRITE_SIZE)

# How fast things move
MOVEMENT_SPEED = 15
JAVELIN_SPEED = 7

# How close the player can get to the edge before wall
VIEWPORT_MARGIN = 300
